version: '3'

services:
  frontend:
    build:
      context:  ./rr
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_API_URL: "http://backend:5000"

  backend:
    build:
      context: ./backk
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      MONGO_URI: "mongodb://database:27017/clinic_reservation"

  database:
    build:
      context: ./database
    volumes:
      - mongodb-data:/data/db 
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
